name: Push-to-build  # When pushing to any branch then run this action
# Env variable
env:
  DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_NAME: ${{ vars.REPO_NAME }}
  BORG_VERSION: ${{ vars.BORG_VERSION }}

on:
  push:
    branches:
    - 'main'

jobs: # job name 
  build-deploy: 
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)     
    steps:
      - name: Check out my repo
        uses: actions/checkout@v4
      - name: take keepalived version
        run: |
          echo "BORG_VERSION=$(curl -s https://archlinux.org/packages/extra/x86_64/borg/ | grep softwareVersion | cut -d '"' -f 4)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'linux/x86_64,linux/arm64,linux/arm/v7'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: 'linux/x86_64,linux/arm64,linux/arm/v7'
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build the Docker image # push The image to the docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ env.REPO_NAME }}:latest,${{ env.REPO_NAME }}:${{ env.BORG_VERSION }}
          platforms: linux/x86_64,linux/arm64,linux/arm/v7
          push: true
